# Copyright 2024 fleming
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: fleming
channels:
    - conda-forge
    - default 
dependencies:
    - python>=3.9,<3.12
    - pytest==7.4.0
    - pytest-mock==3.14.0
    - requests<=2.32.3
    - numpy>=1.23.4,<2.0.0
    - pandas>=1.5.2,<2.2.0
    - black>=24.1.0
    - mkdocs-material==9.5.20
    - mkdocs-material-extensions==1.3.1
    - mkdocstrings==0.25.0
    - mkdocstrings-python==1.10.8
    - mkdocs-macros-plugin==1.0.1
    - openjdk=11
    - pip:
        - databricks-sdk>=0.20.0,<1.0.0 
        - torch>=2.4.1
        - pyspark>=3.3.0,<3.6.0
        - sentence-transformers>=3.2.0
        - mlflow>=2.0.1
